Add workflow success|failure experiment mod

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,13 +11,12 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: step-1 from job-1
-        run:
+        run: |
           echo Hello from job-1, step-1
-          #exit 42
-          exit 1
+          exit 42
 
       - name: step-2 from job-1
-        # if: ${{ success() || failure() }}
+        if: ${{ success() || failure() }}
         run:
           echo Hello from job-1, step-1
 
@@ -34,5 +33,10 @@ jobs:
           echo Hello from job-2, step-2
 
 
-# plain exit-42 on job-1,step-1 and  success()||failure() on job-1,step-2 means job-2 DOES run
-# plain exit-42 on job-1,step-1 and NO success()||failure() on job-1,step-2 means job-1,step-2 DOES run, job-2 DOES run
+# plain exit-42 on job-1,step-1 and success()||failure() on job-1,step-2 means
+#   job-1,step-2 runs?
+#   job-2 runs?
+
+# plain exit-42 on job-1,step-1 and NO success()||failure() on job-1,step-2 means
+#   job-1,step-2 runs?
+#   job-2 runs?
