Try success()||failure()

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,7 +9,7 @@ jobs:
 
   job-1:
     runs-on: ubuntu-latest
-    continue-on-error: true
+    # continue-on-error: true
     steps:
       - name: step-1 from job-1
         run: |
@@ -17,21 +17,21 @@ jobs:
           exit 42
 
       - name: step-2 from job-1
-        # if: ${{ success() || failure() }}
+        if: "(success() || failure())"
         run:
           echo Hello from job-1, step-2
           exit 43
 
       - name: step-3 from job-1
-        # if: ${{ success() || failure() }}
+        if: ${{ success() || failure() }}
         run:
           echo Hello from job-1, step-3
           exit 44
 
   job-2:
     runs-on: ubuntu-latest
-    # if: ${{ success() || failure() }}
     needs: [ job-1 ]
+    if: ${{ success() || failure() }}
     steps:
       - name: step-1 from job-2
         run:
@@ -63,6 +63,7 @@ jobs:
 # With this...
 #  job-2:
 #    runs-on: ubuntu-latest
+#    needs: [ job-1 ]
 #    if: ${{ success() || failure() }}
 # then
 # job1 failed, job2 waits for job1 to finish, and does then run.
@@ -77,4 +78,6 @@ jobs:
 # job1 fails, but job2 is not run (it is skipped)
 
 # Putting continue-on-error: true
-# at the job-1 level
+# at the job-1 level, means that job1 steps 2,3 are not run.
+# and job-1 fails, and job-2 is run.
+
