Try example of continue-on-error at step level

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,6 +11,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: step-1 from job-1
+        continue-on-error: true
         run: |
           echo Hello from job-1, step-1
           exit 42
@@ -18,7 +19,14 @@ jobs:
       - name: step-2 from job-1
         # if: ${{ success() || failure() }}
         run:
-          echo Hello from job-1, step-1
+          echo Hello from job-1, step-2
+          exit 43
+
+      - name: step-3 from job-1
+        # if: ${{ success() || failure() }}
+        run:
+          echo Hello from job-1, step-3
+          exit 44
 
   job-2:
     runs-on: ubuntu-latest
